repos:
  # --- Core Pre-Commit Hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (^docs/|^tests/resources/|^notebooks/|^LICENSE$)
      - id: end-of-file-fixer
        exclude: (^docs/|^tests/resources/|^notebooks/|^LICENSE$)
      - id: check-yaml
        exclude: (^docs/|^notebooks/|^LICENSE$)
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: (^docs/|^tests/resources/|^notebooks/|^LICENSE$)
      - id: check-merge-conflict
      - id: check-toml

  # --- isort (sorting imports) ---
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3
        exclude: (^docs/|^notebooks/|^LICENSE$)

  # --- Ruff Lint & Format ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: (^docs/|^notebooks/|^LICENSE$)

  # --- Black Code Formatter ---
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        exclude: (^docs/|^notebooks/|^LICENSE$)

  # --- Markdown Linting ---
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ['--fix','--config','.markdownlint.yaml']
        exclude: (^docs/|^notebooks/|^LICENSE$|CITATION.cff)

  # --- Codespell ---
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types: [text]
        exclude: (^docs/_build/|^tests/resources/|^build/|^dist/|^notebooks/|^LICENSE$|CITATION.cff)
