repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (^docs/|^tests/resources/|^notebooks/|^LICENSE$)
      - id: end-of-file-fixer
        exclude: (^docs/|^tests/resources/|^notebooks/|^LICENSE$)
      - id: check-yaml
        exclude: (^docs/|^notebooks/|^LICENSE$)
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: check-toml

  # --- Ruff: linting + import sorting ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  # --- Markdown ---
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["--fix","--config",".markdownlint.yaml"]

  # --- Codespell ---
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types: [text]
